### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by RadenAmzar** [sudo-monkey/proton-x50-boot-animation#2]
Hi. I tried to put all the files in USB but the script not running. Do i need to include done.sh also? And inside the folder got another 3 script? Thanks.

**Comment by k8smonkey** [comment]
> Hi. I tried to put all the files in USB but the script not running. Do i need to include done.sh also? And inside the folder got another 3 script? Thanks.

- What OS are you using? I personally have tested on GKUI only. 
- Yes, the done.sh is also required.
- Yes, there are 3 scripts in the same folder.

**Comment by RadenAmzar** [comment]
Mine is ATLAS. i can run app installation script. but boot animation script not running.

**Comment by k8smonkey** [comment]
Both app installation scripts and boot animation scripts have different nature of system permission. You may message me on Facebook for me to understand further the issue. Thanks.

**Comment by RadenAmzar** [comment]
Can you share your facebook account?

**Comment by X50ninja** [comment]
Is there a way for it to work on ATLAS?

**Comment by k8smonkey** [comment]
> Is there a way for it to work on ATLAS? 

Please share the log file

**Comment by X50ninja** [comment]
> > Is there a way for it to work on ATLAS?
> 
> Please share the log file

I dont have the log file.. i wonder if you have the boot animation script for ATLAS.

**Comment by k8smonkey** [comment]
It's for both Atlas and GKUI.

**Comment by RadenAmzar** [comment]
No log file created. When USB plug in to IHU, nothing happened and no log file.

**Comment by X50ninja** [comment]
> No log file created. When USB plug in to IHU, nothing happened and no log file.

Same here.. i copied all the files into usb.. and put my own mp4 video.. also renamed the video to "bootanimation" but the script still wont run..

**Comment by k8smonkey** [comment]
Method 1 (manual trigger the script):

While USB is plugged in, try press and hold the IHU power button for 10 seconds until the IHU rebooted.

**Comment by X50ninja** [comment]
> Method 1 (manual trigger the script):
> 
> While USB is plugged in, try press and hold the IHU power button for 10 seconds until the IHU rebooted.

I did this also but still wont work

**Comment by sudo-monkey** [comment]
Method 2 (removal of GKUI scripts):

- Removed the file xxxfda2.sh from the folder
- Repeat step 1

**Comment by k8smonkey** [comment]
Method 2 (removal of fda2.sh script):
- From the folder, removed the xxxfda2.sh script
- Repeat Method 1

**Comment by X50ninja** [comment]
> Method 2 (removal of fda2.sh script):
> 
> * From the folder, removed the xxxfda2.sh script
> * Repeat Method 1

Sorry but it still wont work for me.. did this too

**Comment by xeon1989** [comment]
@RadenAmzar @X50ninja please try again with the files attached in this reply. 

[proton-x50-boot-animation-main.zip](https://github.com/sudo-monkey/proton-x50-boot-animation/files/13107441/proton-x50-boot-animation-main.zip)

@sudo-monkey There is issue with my macro to calculate the file names for ATLAS.
It has been corrected.
Once confirmed works I raise PR for the correction.
Apologize for the hassle.

**Comment by RadenAmzar** [comment]
@xeon1989 It works for me now. However, the proton logo still appear before the custom .mp4 played, is it normal?

**Comment by k8smonkey** [comment]
> @xeon1989 It works for me now. However, the proton logo still appear before the custom .mp4 played, is it normal?

Yes. It's embedded with the firmware. Glad it's working for Atlas user now, I'm going to close this issue now. Feel free to open new issue separately if any.
